sonar.projectKey=justkits_justkits
sonar.organization=justkits

sonar.sources=apps,design,packages

sonar.typescript.tsconfigPaths=**/*/tsconfig.json

sonar.exclusions=**/node_modules/**,**/dist/**
sonar.coverage.exclusions=**/*.*
sonar.cpd.exclusions=**/tests/**,design/primitives/foundations/src/typography/variables.ts
